[pytest]
testpaths = tests
addopts = -q
filterwarnings =
    ignore::DeprecationWarning:audioread.*
    ignore::DeprecationWarning:librosa.core.intervals
    ignore::DeprecationWarning:aifc
    ignore::DeprecationWarning:audioop
    ignore::DeprecationWarning:sunau
